#pragma once

#include "TrenchParameters.h"

// Generated by tools/bake_move_presets.py.
// Edit C:/Users/hooki/df2/juce-shell/assets/modulation_presets.shipping.json by ear, then rerun the bake script.

namespace trench
{

struct MovePreset
{
    const char* name;
    int   body;
    int   modulation;
    int   shape;
    int   time;
    int   mode;
    float tension;
    float morph;
    float q;
    float slam;
    float outputDb;
    bool  moveOn;
};

inline const MovePreset* movePresets (int& countOut) noexcept
{
    static const MovePreset table[] =
    {
        // name, body, modulation, shape, time, mode, tension, morph, q, slam, outputDb, moveOn
        { "808 Push"        , 1, 0, 0, 0, 3, 0.000f, 0.450f, 0.300f, 0.350f, 0.000f, false },
        { "808 Bounce"      , 1, 1, 0, 0, 3, 0.000f, 0.350f, 0.300f, 0.400f, 0.000f, false },
        { "Drum Bite"       , 0, 0, 0, 0, 3, 0.000f, 0.550f, 0.300f, 0.450f, 0.000f, false },
        { "Drum React"      , 0, 1, 0, 0, 3, 0.000f, 0.400f, 0.300f, 0.500f, 0.000f, false },
        { "Vocal Phone"     , 2, 0, 0, 0, 3, 0.000f, 0.500f, 0.300f, 0.250f, 0.000f, false },
        { "Bass Hollow"     , 3, 0, 0, 0, 3, 0.000f, 0.450f, 0.300f, 0.350f, 0.000f, false },
        { "Loop Pump"       , 3, 1, 0, 0, 3, 0.000f, 0.350f, 0.300f, 0.450f, 0.000f, false },
        { "Synth Sweep"     , 4, 2, 0, 0, 3, 0.000f, 0.500f, 0.300f, 0.200f, 0.000f, false },
        { "Noise Rise"      , 5, 3, 0, 0, 3, 0.000f, 0.600f, 0.300f, 0.300f, 0.000f, false },
        { "Master Pull"     , 4, 0, 0, 0, 3, 0.000f, 0.400f, 0.300f, 0.100f, 0.000f, false },
    };
    countOut = (int) (sizeof (table) / sizeof (table[0]));
    return table;
}

} // namespace trench
