#pragma once
// GENERATED by tools/bake_funcgen_patterns.py - do not hand-edit.
// Emulator X factory Function Generator templates, values normalised to
// peak 1.0 per pattern (DEPTH is the travel dial). Authored data is law.
namespace trench
{
struct FuncGenPattern
{
    const char* name;
    int   steps;        // playable steps (End Step + 1)
    int   direction;    // 0 fwd, 1 rev, 2 pendulum, 3 random, 4 brownian, 5 one-shot
    bool  smooth;       // linear interpolation between steps
    const float* values;    // steps entries, bipolar, peak-normalised
    const unsigned char* trigs; // authored accent cells (unused in v1)
};
inline constexpr float kFgV0[] = { 0.881356f, -0.830508f, 0.000000f, -0.864407f, 1.000000f, -0.423729f, 0.000000f, -0.745763f, 0.949153f, -0.779661f, -0.016949f, -0.593220f, 0.677966f, -0.711864f, 0.830508f, -0.474576f };
inline constexpr unsigned char kFgT0[] = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0 };
inline constexpr float kFgV1[] = { 0.796296f, 0.518519f, 0.296296f, 0.888889f, 0.537037f, 0.259259f, 1.000000f, 0.462963f, 0.870370f, 0.629630f, 0.425926f, 0.981481f, 0.648148f, 0.259259f, 0.777778f, 0.129630f };
inline constexpr unsigned char kFgT1[] = { 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 };
inline constexpr float kFgV2[] = { 0.000000f, -0.500000f, 0.000000f, 1.000000f, -0.500000f, 0.000000f, 0.500000f, -1.000000f, 1.000000f, 0.000000f, 0.500000f, -0.500000f, -1.000000f, 0.000000f, -1.000000f, 0.500000f, -0.500000f, 0.000000f, 1.000000f, 0.000000f, -0.500000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 1.000000f, -1.000000f, 0.500000f, 0.000000f, -0.500000f, -1.000000f, 0.000000f, -0.500000f, 1.000000f, 0.000000f, -1.000000f, 1.000000f, -0.500000f, 0.000000f, 0.500000f, -1.000000f, 0.500000f, -0.500000f, 0.000000f, 1.000000f, 0.500000f, -0.500000f, 0.000000f, -0.520833f, -1.000000f, 0.500000f, -1.000000f, 1.000000f, -0.500000f, 0.000000f, 0.500000f, -1.000000f, 1.000000f, 0.000000f, 0.500000f, 0.000000f, -1.000000f, 0.000000f, 0.500000f };
inline constexpr unsigned char kFgT2[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV3[] = { 1.000000f, -1.000000f, 0.916667f, -0.916667f, 0.833333f, -0.833333f, 0.750000f, -0.750000f, 0.666667f, -0.666667f, 0.583333f, -0.583333f, 0.500000f, -0.500000f, 0.416667f, -0.416667f, 0.333333f, -0.333333f, 0.250000f, -0.250000f, 0.166667f, -0.166667f, 0.083333f, -0.083333f };
inline constexpr unsigned char kFgT3[] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 };
inline constexpr float kFgV4[] = { -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, -1.000000f, 0.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f };
inline constexpr unsigned char kFgT4[] = { 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0 };
inline constexpr float kFgV5[] = { 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.000000f, 0.041667f, 0.104167f, 0.187500f, 0.250000f, 0.333333f, 0.458333f, 0.604167f, 0.770833f, 0.916667f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f, 1.000000f };
inline constexpr unsigned char kFgT5[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
inline constexpr FuncGenPattern kFuncGenPatterns[] = {
    { "BREATHE", 16, 0, true, kFgV0, kFgT0 },
    { "RHYTHM", 16, 0, false, kFgV1, kFgT1 },
    { "WANDER", 64, 4, false, kFgV2, kFgT2 },
    { "ANSWER", 24, 2, false, kFgV3, kFgT3 },
    { "STABS", 16, 0, false, kFgV4, kFgT4 },
    { "RISE", 64, 5, true, kFgV5, kFgT5 },
};
inline constexpr int kNumFuncGenPatterns = 6;
}
