#!/usr/bin/env python3
"""chimera_batch — reference-guided ORIGINAL authoring of whole 4-corner bodies.

The second half of the Chimera workflow. NOT a ROM copier.

Pipeline:
  1. Describe each `--stocks` reference (.bin) -> response descriptors only
     (via tools.chimera_describe_refs; no coefficients are read out as reusable).
  2. BLEND those descriptors into one target recipe (mean band balance, pooled
     peak regions, mean Morph/Q motion, radius guardrail).
  3. GENERATE original whole 4-corner candidates with the repo-safe generator
     (tools.batch_complex.rand_body — peaking-EQ baseline + a motion strategy,
     rolled from a seed). These coefficients come from the generator, never from
     any reference. The blend only RANKS which originals we keep.
  4. Gate each finalist: stability + no-pedestal/response-budget
     (tools.response_budget.judge), plus a similarity-to-stock ORIGINALITY warning
     (a candidate too close to a single stock is flagged, not shipped silently).
  5. Write per-candidate: target recipe, .cart.json, .body240, report.

If the generator cannot produce a single clean candidate, the run STOPS after
writing the target recipes and a clear BLOCKED report. It never fakes bodies.

Run (handoff smoke command):
  python tools/chimera_batch.py --stocks \
      ref/presets/P2k_013_talking_hedz.bin \
      ref/presets/P2k_015_dj_alkaline.bin \
      ref/presets/P2k_031_ear_bender.bin \
      --count 12 --out dev/tmp/chimera_batch_smoke
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import struct
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# ── path discipline (see chimera_describe_refs for why) ──────────────────────
ROOT = Path(__file__).resolve().parents[1]
_HERE = str(Path(__file__).resolve().parent)
sys.path[:] = [p for p in sys.path if p not in ("", _HERE, str(ROOT))]
sys.path.insert(0, str(ROOT))

import numpy as np  # noqa: E402

import tools.chimera_describe_refs as cd  # noqa: E402
import tools.batch_complex as bc  # noqa: E402  (rand_body, cartridge, LABELS, MQ)
import tools.response_budget as rb  # noqa: E402  (judge)
import tools.teleport_stress as ts  # noqa: E402  (verify .body240 round-trip)
from pyruntime.encode import EncodedCoeffs  # noqa: E402
from pyruntime.freq_response import cascade_response_db  # noqa: E402
from pyruntime.packed_interp import packed_bilinear, words_to_coeffs  # noqa: E402

AUTHORING_SR = cd.AUTHORING_SR
FREQS = cd.FREQS
BANDS = cd.BANDS
BAND_NAMES = cd.BAND_NAMES
LABELS = bc.LABELS                      # M0_Q0, M100_Q0, M0_Q100, M100_Q100
CORNER_KEYS = ("A", "B", "C", "D")

REFERENCE_GUIDED_NOTE = (
    "Reference-guided original authoring. The reference .bin files are INTERNAL "
    "guardrails: only their response SHAPE (band balance, peak regions, Morph/Q "
    "motion) steers candidate selection. Candidate coefficients are generated by "
    "tools.batch_complex.rand_body (peaking-EQ + motion); no ROM words, stages, "
    "or coefficients are copied. This is not a claim of legal safety."
)


# ── descriptor helpers (curves already computed once, no recompute) ──────────

def corner_curves(wb: dict[str, list[tuple[int, ...]]]) -> dict[str, np.ndarray]:
    out = {}
    for lab in LABELS:
        enc = [EncodedCoeffs(*words_to_coeffs(w)) for w in wb[lab]]
        out[lab] = cascade_response_db(enc, FREQS, AUTHORING_SR)
    return out


def band_vec(db: np.ndarray) -> np.ndarray:
    return np.array([float(np.mean(db[(FREQS >= lo) & (FREQS < hi)])) for _, lo, hi in BANDS])


def rms(v: np.ndarray) -> float:
    return float(np.sqrt(np.mean(v * v)))


def middle_curve(wb: dict[str, list[tuple[int, ...]]]) -> np.ndarray:
    cw = {CORNER_KEYS[i]: wb[LABELS[i]] for i in range(4)}
    mid = packed_bilinear(cw, 0.5, 0.5)
    return cascade_response_db([EncodedCoeffs(*c) for c in mid], FREQS, AUTHORING_SR)


def peak_freqs(db: np.ndarray, prom: float = 4.0, top: int = 8) -> list[float]:
    return [lm["freq_hz"] for lm in cd.landmarks(db, prom=prom, top=top)["peaks"]]


# ── target blend ─────────────────────────────────────────────────────────────

def build_target(descs: list[dict[str, Any]]) -> dict[str, Any]:
    m0 = np.mean([[d["band_levels_db"]["M0_Q0"][n] for n in BAND_NAMES] for d in descs], axis=0)
    mid = np.mean([[d["band_levels_db"]["middle_M50_Q50"][n] for n in BAND_NAMES] for d in descs], axis=0)
    morph_shift = float(np.mean([d["motion"]["morph_centroid_shift_hz"] for d in descs]))
    q_shift = float(np.mean([d["motion"]["q_centroid_shift_hz"] for d in descs]))
    radius_ceiling = max(d["stability"]["max_pole_radius"] for d in descs)

    pooled: list[tuple[float, float]] = []
    for d in descs:
        for pk in d["landmarks"]["M0_Q0"]["peaks"]:
            pooled.append((pk["freq_hz"], pk["prominence_db"]))
    pooled.sort(key=lambda x: -x[1])
    regions: list[float] = []
    for f, _p in pooled:
        if all(abs(math.log2(f / rf)) > 0.25 for rf in regions):
            regions.append(f)
        if len(regions) >= 6:
            break

    return {
        "band_levels_db": {n: round(float(v), 2) for n, v in zip(BAND_NAMES, m0)},
        "middle_band_levels_db": {n: round(float(v), 2) for n, v in zip(BAND_NAMES, mid)},
        "peak_regions_hz": [round(f, 1) for f in sorted(regions)],
        "morph_centroid_shift_hz": round(morph_shift, 1),
        "q_centroid_shift_hz": round(q_shift, 1),
        "reference_radius_ceiling": round(radius_ceiling, 5),
        "_m0_vec": m0, "_mid_vec": mid,                       # internal, stripped on write
        "_morph_shift": morph_shift, "_peaks": regions,        # internal
    }


def candidate_distance(cand: dict[str, Any], target: dict[str, Any]) -> dict[str, float]:
    d_m0 = rms(cand["m0_vec"] - target["_m0_vec"])
    d_mid = rms(cand["mid_vec"] - target["_mid_vec"])
    d_motion = abs(cand["morph_shift"] - target["_morph_shift"]) / 300.0
    tpk = target["_peaks"]
    if tpk:
        matched = sum(1 for tf in tpk
                      if any(abs(math.log2(cf / tf)) < 0.33 for cf in cand["peaks"]))
        peak_miss = (len(tpk) - matched) / len(tpk)
    else:
        peak_miss = 0.0
    total = d_m0 + 0.5 * d_mid + 1.0 * d_motion + 4.0 * peak_miss
    return {"total": total, "band_rms_db": d_m0, "middle_rms_db": d_mid,
            "motion_term": d_motion, "peak_miss_frac": peak_miss}


# ── generation (repo-safe; original coefficients only) ───────────────────────

def evaluate(wb: dict[str, list[tuple[int, ...]]]) -> dict[str, Any] | None:
    """Gate with the PROVEN generator gate (bc.score: clean on all corners +
    middle, not thin, >=3 peaks), then compute band/peak descriptors for ranking.
    Returns None when the body is rejected by the generator's own clean gate."""
    if bc.score(wb) is None:
        return None
    curves = corner_curves(wb)
    mid_db = middle_curve(wb)
    return {
        "m0_vec": band_vec(curves["M0_Q0"]),
        "mid_vec": band_vec(mid_db),
        "peaks": peak_freqs(mid_db),
        "morph_shift": cd.centroid_hz(curves["M100_Q0"]) - cd.centroid_hz(curves["M0_Q0"]),
    }


PEAK_TARGET_DB = -3.0  # land the M0_Q0 peak here so it sits in headroom (budget peak-sane)


def derive_boost(wb: dict[str, list[tuple[int, ...]]]) -> float:
    """Gain derived AFTER the shape passes (response-first doctrine): scale so the
    M0_Q0 peak lands at PEAK_TARGET_DB. Post-filter gain only — does not touch the
    poles/zeros/shape or the .body240 words. Clamped to a sane range."""
    enc = [EncodedCoeffs(*words_to_coeffs(w)) for w in wb["M0_Q0"]]
    peak = float(cascade_response_db(enc, FREQS, AUTHORING_SR).max())
    return float(min(max(10.0 ** ((PEAK_TARGET_DB - peak) / 20.0), 0.02), 32.0))


def body240_bytes(wb: dict[str, list[tuple[int, ...]]]) -> bytes:
    """Raw 240-byte body: corners M0_Q0/M100_Q0/M0_Q100/M100_Q100, 6 stages x 5 u16 LE."""
    buf = bytearray()
    for lab in LABELS:
        for stage in wb[lab]:
            for w in stage:
                buf += struct.pack("<H", int(w) & 0xFFFF)
    return bytes(buf)


def shared_rows_with_refs(wb, stock_bodies) -> int:
    """Count candidate stage-rows (5-word tuples) that appear verbatim in any
    reference body. Generated EQ words should share NONE — proof of no copying."""
    cand_rows = {tuple(int(w) & 0xFFFF for w in stage) for lab in LABELS for stage in wb[lab]}
    ref_rows = set()
    for corners in stock_bodies:
        for key in CORNER_KEYS:
            for stage in corners[key]:
                ref_rows.add(tuple(int(w) & 0xFFFF for w in stage))
    return len(cand_rows & ref_rows)


# ── output ───────────────────────────────────────────────────────────────────

README = """# Chimera batch — reference-guided ORIGINAL bodies

## What these files are
- **References are internal guardrails only.** The P2K/ROM `.bin` files were read
  for their response *shape* (band balance, peak regions, Morph/Q motion). Their
  shape steered which random-original candidates we kept. **No ROM words, stages,
  or coefficients were copied into any candidate.** This is reference-guided
  original authoring — not a claim of legal safety.
- Each `cand_NN/` holds an **original whole 4-corner body**:
  - `target_recipe.json` — the blended target this candidate was selected toward.
  - `*.cart.json` + `*.body240` — the generated body (240-byte packed + compiled-v1).
  - `report.json` — stability, no-pedestal/response-budget result, similarity-to-
    stock originality warning, and an audition-notes placeholder.

## What you do next (the ear is the only fitness function)
1. **Audition every candidate in Forge** with the SAW / TONE / PINK sources — not
   on paper. The descriptors are a starting filter, never the verdict.
2. Listen across HOME -> MORPH -> TENSION -> MORPH+TENSION and the middle.
3. **Final keep / delete / polish happens in Forge / DRAW**, by ear. Push any body
   flagged "similar to stock" further so it stands on its own, or cut it.

Candidates that fire stay; the rest get deleted. Nothing here ships until it has
passed your ear in Forge.
"""


def write_blocked(out_dir: Path, target: dict, stocks_desc: list[dict], reason: str) -> None:
    (out_dir / "BLOCKED.md").write_text(
        "# Chimera batch — BLOCKED\n\n"
        f"{reason}\n\n"
        "Target recipes were written, but **no candidate bodies were generated**. "
        "Per the workflow contract, bodies are never faked to fill the count. "
        "Re-run with a larger `--pool`, a different `--base` seed, or relax the "
        "generator gate.\n\n"
        "See `target_recipe.json` for the blended target.\n",
        encoding="utf-8",
    )
    clean = {k: v for k, v in target.items() if not k.startswith("_")}
    (out_dir / "target_recipe.json").write_text(json.dumps({
        "tool": "chimera_batch",
        "status": "blocked",
        "reuse_policy": REFERENCE_GUIDED_NOTE,
        "blended_target": clean,
        "stocks": [{"id": d["provenance"]["manifest_id"],
                    "name": d["provenance"]["manifest_name"],
                    "role": "guardrail only"} for d in stocks_desc],
    }, indent=2), encoding="utf-8")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stocks", nargs="+", required=True, type=Path,
                    help="reference .bin files used as guardrails (NOT copied)")
    ap.add_argument("--count", type=int, default=12, help="candidate bodies to keep")
    ap.add_argument("--out", type=Path, required=True, help="output directory")
    ap.add_argument("--pool", type=int, default=0,
                    help="seeds to search (default: max(3000, count*200))")
    ap.add_argument("--base", type=int, default=1, help="seed base (reproducible)")
    ap.add_argument("--similarity-warn-db", type=float, default=3.0,
                    help="band-RMS below this to ANY single stock = originality warning")
    args = ap.parse_args(argv)

    out_dir = args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    pool = args.pool or max(3000, args.count * 200)

    # 1. describe stocks (response shape only) + keep raw bodies for the no-copy proof
    manifest = cd.load_manifest()
    stocks_desc: list[dict] = []
    stock_bodies: list[dict] = []
    stock_m0: list[np.ndarray] = []
    for p in args.stocks:
        if not p.exists():
            print(f"SKIP (missing stock): {p}", file=sys.stderr)
            continue
        stocks_desc.append(cd.describe_ref(p, manifest))
        _, corners = ts.load_packed_body(p)
        stock_bodies.append(corners)
        stock_m0.append(np.array([stocks_desc[-1]["band_levels_db"]["M0_Q0"][n] for n in BAND_NAMES]))
    if not stocks_desc:
        print("ERROR: no readable stock references.", file=sys.stderr)
        return 1

    # 2. blend
    target = build_target(stocks_desc)
    print("blended target  low/body/bite/air = "
          + "/".join(f"{target['band_levels_db'][n]:+.1f}" for n in BAND_NAMES)
          + f"   peak regions(Hz)={target['peak_regions_hz']}"
          + f"   morph shift={target['morph_centroid_shift_hz']:+.0f}Hz")

    # 3. generate original candidates, rank by closeness to the blend
    print(f"searching {pool} seeds (base {args.base}) for originals near the target ...")
    kept: list[dict] = []
    for i in range(pool):
        seed = args.base * bc.SEED_STRIDE + i
        wb, motion = bc.rand_body(random.Random(seed))
        ev = evaluate(wb)
        if ev is None:
            continue
        dist = candidate_distance(ev, target)
        kept.append({"seed": seed, "motion": motion, "dist": dist["total"],
                     "dist_breakdown": dist, "ev": ev})
    kept.sort(key=lambda k: k["dist"])

    if not kept:
        write_blocked(out_dir, target, stocks_desc,
                      reason=f"The generator produced 0 clean candidates over {pool} seeds "
                             "(all rejected by the no-pedestal / clean-response gate).")
        print("BLOCKED: 0 clean candidates. Wrote target recipe + BLOCKED.md. No bodies faked.")
        return 0

    finalists = kept[:args.count]
    clean_target = {k: v for k, v in target.items() if not k.startswith("_")}

    # 4 + 5. write each candidate dir
    manifest_rows = []
    for rank, item in enumerate(finalists, 1):
        name = f"chimera_{rank:02d}"
        wb, _ = bc.rand_body(random.Random(item["seed"]))  # regenerate (reproducible)
        cdir = out_dir / f"cand_{rank:02d}"
        cdir.mkdir(parents=True, exist_ok=True)

        boost = derive_boost(wb)
        cart = bc.cartridge(name, wb)
        cart["provenance"] = "chimera reference-guided original authoring"
        cart["boost"] = boost
        for kf in cart["keyframes"]:
            kf["boost"] = boost
        cart_path = cdir / f"{name}.cart.json"
        cart_path.write_text(json.dumps(cart, indent=2), encoding="utf-8")

        raw = body240_bytes(wb)
        raw_path = cdir / f"{name}.body240"
        raw_path.write_bytes(raw)

        # verify the .body240 reloads to the SAME words as the cart (one packed path)
        _, reload = ts.load_packed_body(raw_path)
        cw_cart = {CORNER_KEYS[i]: [tuple(int(x) & 0xFFFF for x in w) for w in wb[LABELS[i]]]
                   for i in range(4)}
        body_matches = all(reload[k] == cw_cart[k] for k in CORNER_KEYS)

        # authoritative gate: stability + no-pedestal/response-budget
        verdict = rb.judge(str(cart_path))

        # originality: distance to the NEAREST single stock
        sims = [rms(item["ev"]["m0_vec"] - sm0) for sm0 in stock_m0]
        nearest = int(np.argmin(sims))
        sim_db = float(sims[nearest])
        too_close = sim_db < args.similarity_warn_db
        nearest_name = stocks_desc[nearest]["provenance"]["manifest_name"]

        shared = shared_rows_with_refs(wb, stock_bodies)

        target_recipe = {
            "tool": "chimera_batch",
            "candidate": name,
            "reuse_policy": REFERENCE_GUIDED_NOTE,
            "blended_target": clean_target,
            "stocks": [{"id": d["provenance"]["manifest_id"],
                        "name": d["provenance"]["manifest_name"],
                        "role": "guardrail only"} for d in stocks_desc],
            "candidate_descriptor": {
                "seed": item["seed"],
                "motion_strategy": item["motion"],
                "M0_Q0_band_levels_db": {n: round(float(v), 2)
                                         for n, v in zip(BAND_NAMES, item["ev"]["m0_vec"])},
                "middle_band_levels_db": {n: round(float(v), 2)
                                          for n, v in zip(BAND_NAMES, item["ev"]["mid_vec"])},
                "middle_peak_regions_hz": [round(f, 1) for f in item["ev"]["peaks"][:6]],
                "morph_centroid_shift_hz": round(item["ev"]["morph_shift"], 1),
                "derived_boost": round(boost, 4),
            },
            "distance_to_target": {k: round(v, 3) for k, v in item["dist_breakdown"].items()},
        }
        (cdir / "target_recipe.json").write_text(json.dumps(target_recipe, indent=2),
                                                 encoding="utf-8")

        report = {
            "candidate": name,
            "seed": item["seed"],
            "motion_strategy": item["motion"],
            "derived_boost": round(boost, 4),
            "origin": "generated original (tools.batch_complex.rand_body) — no ROM data copied",
            "no_copied_rom_words": shared == 0,
            "shared_stage_rows_with_refs": shared,
            "stability": {
                "max_pole_radius": verdict["max_radius"],
                "stable": verdict["gates"]["stable"],
                "near_edge_warning": 0.985 <= verdict["max_radius"] < 1.0,
                "note": "near-edge radius is heat, not a reject, unless unstable",
            },
            "response_budget": {
                "pass": verdict["pass"],
                "gates": verdict["gates"],
                "bands_db": verdict["bands"],
                "no_pedestal": verdict["gates"]["no-pedestal"],
                "dc_diag_max_db": verdict["dc_diag_max_db"],
            },
            "similarity_to_stock": {
                "nearest_stock": nearest_name,
                "band_rms_db": round(sim_db, 2),
                "warning": too_close,
                "message": (f"Resembles '{nearest_name}' (band RMS {sim_db:.1f} dB < "
                            f"{args.similarity_warn_db} dB). Push further in DRAW or re-roll "
                            "for originality." if too_close else
                            f"Distinct from nearest stock '{nearest_name}' "
                            f"(band RMS {sim_db:.1f} dB)."),
            },
            "body240": {
                "bytes": len(raw),
                "sha256": hashlib.sha256(raw).hexdigest(),
                "reloads_identical_to_cart": body_matches,
            },
            "audition_notes": "",  # PLACEHOLDER — fill after auditioning in Forge (SAW/TONE/PINK)
            "audition_instruction": ("Open in Forge, audition with SAW/TONE/PINK across "
                                     "HOME->MORPH->TENSION->MORPH+TENSION and the middle. "
                                     "Keep/delete/polish by ear in DRAW."),
        }
        (cdir / "report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

        manifest_rows.append({
            "candidate": name, "dir": f"cand_{rank:02d}", "seed": item["seed"],
            "motion": item["motion"], "distance": round(item["dist"], 3),
            "max_radius": verdict["max_radius"], "budget_pass": verdict["pass"],
            "no_copied_rom_words": shared == 0,
            "similar_to_stock": nearest_name if too_close else None,
            "similarity_band_rms_db": round(sim_db, 2),
        })
        flag = "  SIMILAR!" if too_close else ""
        edge = "  near-edge" if (0.985 <= verdict["max_radius"] < 1.0) else ""
        print(f"  {name}: {item['motion']:11s} dist={item['dist']:5.2f} "
              f"maxR={verdict['max_radius']:.4f}{edge} budget={'PASS' if verdict['pass'] else 'FAIL'} "
              f"copied_rom={shared} sim={sim_db:4.1f}dB->{nearest_name}{flag}")

    # batch-level artifacts
    (out_dir / "README.md").write_text(README, encoding="utf-8")
    (out_dir / "batch_manifest.json").write_text(json.dumps({
        "tool": "chimera_batch",
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "status": "ok",
        "reuse_policy": REFERENCE_GUIDED_NOTE,
        "stocks": [{"file": str(p).replace("\\", "/"),
                    "id": d["provenance"]["manifest_id"],
                    "name": d["provenance"]["manifest_name"],
                    "role": "INTERNAL GUARDRAIL ONLY — not copied"}
                   for p, d in zip(args.stocks, stocks_desc)],
        "blended_target": clean_target,
        "search_pool": pool,
        "base_seed": args.base,
        "kept": len(finalists),
        "clean_candidates_found": len(kept),
        "candidates": manifest_rows,
    }, indent=2), encoding="utf-8")

    n_pass = sum(1 for r in manifest_rows if r["budget_pass"])
    n_orig = sum(1 for r in manifest_rows if r["no_copied_rom_words"])
    n_sim = sum(1 for r in manifest_rows if r["similar_to_stock"])
    print(f"\nwrote {len(finalists)} candidates -> {out_dir}")
    print(f"  budget PASS: {n_pass}/{len(finalists)}   no-copied-ROM: {n_orig}/{len(finalists)}"
          f"   similarity warnings: {n_sim}")
    print("  AUDITION REQUIRED in Forge (SAW/TONE/PINK). See README.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
